# Generated by Django 5.0.1 on 2024-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='body',
            new_name='descriptions',
        ),
        migrations.AddField(
            model_name='new',
            name='content',
            field=models.TextField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=350),
        ),
    ]
